### ISSUE TITLE
NPE (and rage quit) on server start-up

### ISSUE THREAD

**Issue by SlimeDog** [MeGysssTaa/keiko-plugin-inspector#1]
Spigot 1.15.2 (Jenkins 2692)
Keiko 2.1.0

New clean installation of Keiko. Obviously, one cannot run Keiko out of the box. :(
But NPEs?
````
[10:02:50] [Server thread/INFO]: Starting minecraft server version 1.15.2
[10:02:50] [Server thread/INFO]: Loading properties
[10:02:51] [Server thread/INFO]: This server is running CraftBukkit version git-Spigot-a99063f-fad2494 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
[10:02:51] [Server thread/INFO]: Debug logging is disabled
[10:02:51] [Server thread/INFO]: Using 4 threads for Netty based IO
[10:02:51] [Server thread/INFO]: Server Ping Player Sample Count: 12
[10:02:51] [Server thread/INFO]: Default game type: SURVIVAL
[10:02:51] [Server thread/INFO]: Generating keypair
[10:02:51] [Server thread/INFO]: Starting Minecraft server on *:25565
[10:02:51] [Server thread/INFO]: Using epoll channel type
[10:02:53] [Server thread/WARN]: Initializing Legacy Material Support. Unless you have legacy plugins and/or data this is a bug!
[10:02:59] [Server thread/WARN]: Legacy plugin PluginManager v2.0 does not specify an api-version.
[10:02:59] [Server thread/WARN]: Legacy plugin WeaponHolder v1.5 does not specify an api-version.
[10:02:59] [Server thread/WARN]: Legacy plugin NetworkInterceptor v1.0-SNAPSHOT does not specify an api-version.
[10:02:59] [Server thread/INFO]: [NetworkInterceptor] Using blacklist blocking strategy
[10:02:59] [Server thread/INFO]: [NetworkInterceptor] Using file logger
[10:02:59] [Server thread/INFO]: [NetworkInterceptor] Interceptors: [PROXY_SELECTOR]
[10:02:59] [Server thread/INFO]: [NetworkInterceptor] [ProxySelectorInterceptor] Replacing 'sun.net.spi.DefaultProxySelector' selector with logged variant.
[10:02:59] [Server thread/WARN]: Legacy plugin WhatPlugin v1.0-SNAPSHOT (build #3) does not specify an api-version.
[10:02:59] [Server thread/WARN]: Legacy plugin EntityList v1.0 does not specify an api-version.
[10:02:59] [Server thread/WARN]: Legacy plugin RedstoneDetector v0.3 does not specify an api-version.
[10:02:59] [Server thread/WARN]: Legacy plugin ViaVersion v2.2.3 does not specify an api-version.
[10:02:59] [Server thread/WARN]: Legacy plugin AdvancedReplay v1.5.2 does not specify an api-version.
[10:02:59] [Server thread/WARN]: Legacy plugin DelayJoin v1.0-SNAPSHOT does not specify an api-version.
[10:02:59] [Server thread/WARN]: Legacy plugin UsernameHistory v1.2 does not specify an api-version.
[10:02:59] [Server thread/INFO]: [Keiko] INFO    :  Performing early boot... [bukkit]
[10:02:59] [Server thread/WARN]: [Keiko] WARNING :
[10:02:59] [Server thread/WARN]: [Keiko] WARNING :  ======================================================================
[10:02:59] [Server thread/WARN]: [Keiko] WARNING :    (!) IMPORTANT: You are running Keiko on Bukkit.
[10:02:59] [Server thread/WARN]: [Keiko] WARNING :        This means that Keiko will only inspect plugins installed on
[10:02:59] [Server thread/WARN]: [Keiko] WARNING :        this certain Bukkit server, and if you are using BungeeCord,
[10:02:59] [Server thread/WARN]: [Keiko] WARNING :        Bungee plugins will NOT be checked! You should install Keiko
[10:02:59] [Server thread/WARN]: [Keiko] WARNING :        on the Bungee itself too if you are using it (make sure to have
[10:02:59] [Server thread/WARN]: [Keiko] WARNING :        Keiko installed both on Bungee and ALL its 'child' servers).
[10:02:59] [Server thread/WARN]: [Keiko] WARNING :  ======================================================================
[10:02:59] [Server thread/WARN]: [Keiko] WARNING :
[10:02:59] [Server thread/INFO]: [Keiko] INFO    :  Indexing plugins...
[10:02:59] [Server thread/WARN]: [Keiko] WARNING :  Invalid plugin.yml in Multiverse-Inventories-4.0.0-b469.jar
[10:02:59] [Server thread/WARN]: [Keiko] WARNING :  Invalid plugin Multiverse-Inventories-4.0.0-b469.jar: missing 'name' in plugin.yml (or no plugin.yml)
[10:03:00] [Server thread/INFO]: [Keiko] INFO    :  Successfully indexed 155 plugins.
[10:03:00] [Server thread/INFO]: [Keiko] INFO    :  Running static analysis in folder /home/ram/Spigot/plugins. This may take some time...
[10:03:00] [Server thread/INFO]: [Keiko] INFO    :  File /home/ram/Spigot/plugins/AAC-4.3.12.jar has not been inspected for a long period of time or at all. It may take slight time to analyze it...
[10:03:01] [Server thread/INFO]: [Keiko] INFO    :  File /home/ram/Spigot/plugins/ConsoleSpamFix-1.8.2.jar has not been inspected for a long period of time or at all. It may take slight time to analyze it...
[10:03:02] [Server thread/INFO]: [Keiko] INFO    :  File /home/ram/Spigot/plugins/ExtraContexts-1.0-b13.jar has not been inspected for a long period of time or at all. It may take slight time to analyze it...
[10:03:02] [Server thread/INFO]: [Keiko] INFO    :  File /home/ram/Spigot/plugins/CommandSigns-2.2.0-beta.jar has not been inspected for a long period of time or at all. It may take slight time to analyze it...
[10:03:03] [Server thread/WARN]: [Keiko] WARNING :  JAR CommandSigns-2.2.0-beta.jar is likely MALICIOUS (confidence: 100.0%)! Details: Static.ForceOp[detected OP-giving Bukkit API usage in method interpretOpCommand declared in class be/nokorbis/spigot/commandsigns/controller/executions/CommandsRunner]. It is adviced that you delete it.
[10:03:04] [Server thread/WARN]: java.lang.NullPointerException
[10:03:04] [Server thread/WARN]:        at me.darksidecode.keiko.pluginsintegrity.PluginsIntegrityChecker.checkIntegrity(PluginsIntegrityChecker.java:34)
[10:03:04] [Server thread/WARN]:        at me.darksidecode.keiko.KeikoPluginInspector.runStaticCheck(KeikoPluginInspector.java:177)
[10:03:04] [Server thread/WARN]:        at me.darksidecode.keiko.KeikoPluginInspector.earlyBoot(KeikoPluginInspector.java:134)
[10:03:04] [Server thread/WARN]:        at me.darksidecode.keiko.KeikoBukkit.<clinit>(KeikoBukkit.java:28)
[10:03:04] [Server thread/WARN]:        at java.base/java.lang.Class.forName0(Native Method)
[10:03:04] [Server thread/WARN]:        at java.base/java.lang.Class.forName(Class.java:398)
[10:03:04] [Server thread/WARN]:        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64)
[10:03:04] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135)
[10:03:04] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:394)
[10:03:04] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:301)
[10:03:04] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.loadPlugins(CraftServer.java:353)
[10:03:04] [Server thread/WARN]:        at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:210)
[10:03:04] [Server thread/WARN]:        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:784)
[10:03:04] [Server thread/WARN]:        at java.base/java.lang.Thread.run(Thread.java:834)
[10:03:04] [Server thread/WARN]: [Keiko] WARNING :  The server will be shut down forcefully (rage quit).
[10:03:04] [Server thread/WARN]: [Keiko] WARNING :  Sending SIGKILL(9) to process 10860 (rage quit)
```

**Comment by SlimeDog** [comment]
Setting global configuration parameter values more leniently, and trying again...

Too many failures on the most trusted plugins. Giving it a pass until I have more time to study the configuration requirements.

**Comment by SlimeDog** [comment]
Assuming I wanted to accept all of the following (a questionable assumption, but hopefully useful examples), what would the configuration look like?
```
[10:19:46.482] WARNING :  JAR CommandSigns-2.2.0-beta.jar is likely MALICIOUS (confidence: 100.0%)! Details: Static.ForceOp[detected OP-giving Bukkit API usage in method interpretOpCommand declared in class be/nokorbis/spigot/commandsigns/controller/executions/CommandsRunner]. It is adviced that you delete it.
[10:19:48.303] WARNING :  The server will be shut down forcefully (rage quit).
[10:19:56.251] WARNING :  Detected security violation by [plugin: AAC, class: me.konsolas.aac.AAC, method: <clinit>] on operation FILE_READ (File: /usr/local/jdk-11.0.6/lib/libsunec.so)
[10:19:56.408] WARNING :  Detected security violation by [plugin: AAC, class: me.konsolas.aac.AAC, method: <clinit>] on operation FILE_READ (File: /usr/local/jdk-11.0.6/conf/security/policy/unlimited)
[10:19:59.305] WARNING :  Detected security violation by [plugin: WorldEdit, class: com.sk89q.worldedit.slf4j.LoggerFactory, method: findPossibleStaticLoggerBinderPathSet] on operation FILE_READ (File: /home/ram/Spigot/plugins/truezip.jar)
[10:19:59.328] WARNING :  Detected security violation by [plugin: WorldEdit, class: com.sk89q.worldedit.slf4j.LoggerFactory, method: findPossibleStaticLoggerBinderPathSet] on operation FILE_READ (File: /home/ram/Spigot/plugins/truevfs.jar)
[10:19:59.348] WARNING :  Detected security violation by [plugin: WorldEdit, class: com.sk89q.worldedit.slf4j.LoggerFactory, method: findPossibleStaticLoggerBinderPathSet] on operation FILE_READ (File: /home/ram/Spigot/plugins/js.jar)
[10:20:07.279] WARNING :  Detected an attempt to perform a restricted action setContextClassLoader by [plugin: LuckPerms, class: me.lucko.luckperms.common.dependencies.DependencyManager, method: loadDependencies].
[10:20:07.453] WARNING :  Detected security violation by [plugin: BloodMoon, class: com.google.common.io.CharSource, method: read] on operation FILE_READ (File: /home/ram/Spigot/plugins/ProtocolLib/lastupdate)
[10:20:08.221] WARNING :  Detected security violation by [plugin: WorldEdit, class: com.sk89q.worldedit.command.util.CommandPermissionsConditionGenerator, method: generateCondition] on operation FILE_READ (File: /home/ram/Spigot/plugins/Depenizen-2.0.0-b623.jar)
[10:20:09.127] WARNING :  Detected security violation by [plugin: BloodMoon, class: com.google.common.io.Files, method: createParentDirs] on operation FILE_READ (File: /home/ram/Spigot/plugins/NewAmazingLuckyBlocks)
[10:20:09.938] WARNING :  Detected security violation by [plugin: VarLight, class: me.shawlaf.varlight.spigot.VarLightPlugin, method: onLoad] on operation FILE_READ (File: /home/ram/Spigot/./UNIVERSE/world/datapacks)
[10:20:11.599] WARNING :  Detected security violation by [plugin: BloodMoon, class: com.google.common.io.Files, method: createParentDirs] on operation FILE_READ (File: /home/ram/Spigot/plugins/Vault)
[10:20:12.219] WARNING :  Detected security violation by [plugin: BloodMoon, class: com.google.common.io.Files, method: createParentDirs] on operation FILE_READ (File: /home/ram/Spigot/plugins/Orebfuscator4)
[10:20:12.331] WARNING :  Detected security violation by [plugin: WorldEdit, class: com.sk89q.wepif.PermissionsResolverManager, method: loadConfig] on operation FILE_READ (File: /home/ram/Spigot/wepif.yml)
[10:20:12.433] WARNING :  Detected security violation by [plugin: BloodMoon, class: com.google.common.io.Files, method: createParentDirs] on operation FILE_READ (File: /home/ram/Spigot/plugins/CityWorld)
[10:20:13.071] WARNING :  Detected security violation by [plugin: BloodMoon, class: com.google.common.io.Files, method: createParentDirs] on operation FILE_READ (File: /home/ram/Spigot/plugins/BentoBox/locales/BentoBox)
[10:20:13.172] WARNING :  Detected security violation by [plugin: BloodMoon, class: com.google.common.io.Files, method: newWriter] on operation FILE_WRITE (File: /home/ram/Spigot/./UNIVERSE/usercache.json)
[10:20:13.245] WARNING :  Detected security violation by [plugin: BloodMoon, class: com.google.common.io.Files, method: createParentDirs] on operation FILE_READ (File: /home/ram/Spigot/plugins/CityWorld)
[10:20:13.433] WARNING :  Detected an attempt to perform a restricted action setProxySelector by [plugin: NetworkInterceptor, class: me.lucko.networkinterceptor.interceptors.ProxySelectorInterceptor, method: disable].
```

**Comment by MeGysssTaa** [comment]
1. NPE — it looks like one of your plugins has no `name` in its `plugin.yml`. Are there any such warnings in your console or Keiko logs? If so, could you please check that plugin and look if the `name` is actually there?
2. Ragequit — `[Keiko] WARNING :  JAR CommandSigns-2.2.0-beta.jar is likely MALICIOUS (confidence: 100.0%)! Details: Static.ForceOp[detected OP-giving Bukkit API usage in method interpretOpCommand declared in class be/nokorbis/spigot/commandsigns/controller/executions/CommandsRunner]. It is adviced that you delete it.` Keiko detected plain invocation of Bukkit's method `Player#setOp` in the reported class. Please check it (using any decompiler) and check what the code does. If you're 100% sure it's not malicious, you can add this particular plugin in **ForceOP exclusions** (`inspections.yml`).
3. If you want Keiko to allow all plugins to **read** (but not write) **any** files on your machine, set the `default` rule for operation `file_read` in config `runtimeprotect.yml` to **`ALLOW`**. Then, if you want Keiko to restrict all or particular plugins from reading some **particular files**, you can add some special rules under `rules` list, like so:
```yaml
file_read:
  notify: false
  default: ALLOW
  rules:
    # All plugins will be able to read all files, except for the file named
    # "some-secret-file.txt" located in your server folder (where the startup JAR is).
    - DENY ALL {server_folder}/some-secret-file.txt
```

For details on configuring **Keiko DAC** see **[wiki](https://github.com/MeGysssTaa/keiko-plugin-inspector/wiki/Domain-Access-Control)** or **[join Keiko's Discord^^](https://discord.gg/QWHzCXX)**

**Comment by SlimeDog** [comment]
> 1. NPE — it looks like one of your plugins has no `name` in its `plugin.yml`. Are there any such warnings in your console or Keiko logs? If so, could you please check that plugin and look if the `name` is actually there?

Part A: plugin.yml contains:
```
name: Multiverse-Inventories
main: com.onarandombox.multiverseinventories.MultiverseInventories
version: 4.0.0-SNAPSHOT-b469
api-version: 1.13
author: dumptruckman
depend: ['Multiverse-Core']
softdepend: [MultiInv, WorldInventories, Multiverse-Adventure]

commands:
...
```
Multiverse-Inventoriers loads, enables, and operates without ERROR or WARN reports.

Part B: The NPE does not seem related to that issue. It occurred 5 seconds later in the log, after  other reported issues.

**Comment by SlimeDog** [comment]
> 2. Ragequit — ... Please check it (using any decompiler) and check what the code does. If you're 100% sure it's not malicious, you can add this particular plugin in **ForceOP exclusions** (`inspections.yml`).

Thanks. Done.

**Comment by SlimeDog** [comment]
> 3. If you want Keiko to allow all plugins to **read** (but not write) **any** files on your machine, set the `default` rule for operation `file_read` in config `runtimeprotect.yml` to **`ALLOW`**. 

Thanks. It's not clear that should be allowed. I will address the purpose of the apparently-arbitrary file reads with the developer.

**Comment by MeGysssTaa** [comment]
>I will address the purpose of the apparently-arbitrary file reads with the developer.

Please note that files in **`/usr/local/jdk-11.0.6/`** should usually be allowed for all plugins to read, because some files there are read internally by various Java APIs, for example, encryption.

Plugin `BloodMoon` appears to be manipulating with many plugins at the same time (e.g. `CityWorld`, `BentoBox`). I'm not sure what all these plugins are so can't tell if this is OK in your case.

**Comment by SlimeDog** [comment]
> Plugin BloodMoon appears to be manipulating with many plugins at the same time (e.g. CityWorld, BentoBox). I'm not sure what all these plugins are so can't tell if this is OK in your case.

They are all world generators/manipulators. So BloodMoon `may` have to understand them.

**Comment by SlimeDog** [comment]
Closed due to disinterest. We no longer use this plugin.
